'use strict';

angular.module('app', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngMessages',
    'ngTouch',
    'ngStorage',
    'ui-sreach',
    'ui.router',
    'ui.bootstrap',
    'ui.load',
    'ui.jq',
    'ui.validate',
    'oc.lazyLoad',
    'ui-laydate',
    'sky-validate',
    'pascalprecht.translate',
    'FakeHttpBackend',
    'ui.grid',
    'ui.grid.selection',
    'ui.grid.edit',
    'ui.grid.pagination',
    'ui.grid.resizeColumns',
    'ui.grid.autoResize',
    'ngDialog',
    'toaster'
]);